export const ERROR = 'ERROR';

export const SET_FILTER = 'SET_FILTER';

export const TOGGLE_SELECTED = 'TOGGLE_SELECTED';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

export const DELETE_USER = 'DELETE';
export const DELETE_USER_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_USER_FAILED= 'DELETE_FAILED';

export const SEND = 'SEND';
export const SEND_SUCCESS = 'SEND_SUCCESS';
export const SEND_FAILED = 'SEND_FAILED';
